version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_PATH}/config/jellyfin:/config
      - ${ROOT_PATH}/data/media/tv:/data/tvshows
      - ${ROOT_PATH}/data/media/movies:/data/movies
    ports:
      - "8096:8096" # Web UI
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_PATH}/config/prowlarr:/config
    ports:
      - "9696:9696" # Web UI
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_PATH}/config/radarr:/config
      - ${ROOT_PATH}/data:/data # Mount the entire data folder
    ports:
      - "7878:7878" # Web UI
    depends_on:
      - prowlarr
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_PATH}/config/sonarr:/config
      - ${ROOT_PATH}/data:/data # Mount the entire data folder
    ports:
      - "8989:8989" # Web UI
    depends_on:
      - prowlarr
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${ROOT_PATH}/config/qbittorrent:/config
      - ${ROOT_PATH}/data/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ${ROOT_PATH}/config/jellyseerr:/app/config
    ports:
      - "5055:5055" # Web UI
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped
